import { EAProfile } from "./types";

export const MOCK_EA_PROFILES: EAProfile[] = [
  {
    id: "ea-001",
    name: "RSI SCALPER",
    status: "RUNNING",
    strategyType: "SCALPING",
    symbols: ["EURUSD"],
    timeframes: ["M1", "M5"],
    magicNumber: 10001,
    aiRecommendation: {
      recommendation: "RECOMMENDED",
      marketCompatibility: 87,
      reasons: [
        "現在のボラティリティはスキャルピング戦略に適合",
        "RSIダイバージェンスシグナルが明確",
        "スプレッド条件が良好",
        "現セッション中に重要ニュースリスクなし",
      ],
    },
    performance: {
      totalTrades: 342,
      winRate: 61.4,
      totalPips: 486.3,
      profitFactor: 1.42,
      avgPips: 1.4,
      maxDrawdown: 8.2,
    },
    sessionPerformance: [
      { session: "TOKYO",    winRate: 58.1, pips: 112.4 },
      { session: "LONDON",   winRate: 64.3, pips: 214.6 },
      { session: "NEW_YORK", winRate: 61.8, pips: 159.3 },
    ],
    lossPatterns: [
      { name: "高スプレッド時の逆行",   lossRate: 22, impact: "HIGH"   },
      { name: "ニュース時のヒゲ刺し",   lossRate: 15, impact: "MEDIUM" },
      { name: "アジア時間のドリフト",   lossRate: 9,  impact: "LOW"    },
    ],
  },
  {
    id: "ea-002",
    name: "GOLD MOMENTUM",
    status: "STOPPED",
    strategyType: "SCALPING",
    symbols: ["XAUUSD"],
    timeframes: ["M5"],
    magicNumber: 10002,
    aiRecommendation: {
      recommendation: "CAUTION",
      marketCompatibility: 52,
      reasons: [
        "金ボラティリティ高騰中 — スプレッドリスクが高い",
        "モメンタムシグナルが相反している",
        "現セッションに高インパクト指標と重複",
      ],
    },
    performance: {
      totalTrades: 198,
      winRate: 54.2,
      totalPips: 214.8,
      profitFactor: 1.18,
      avgPips: 1.1,
      maxDrawdown: 14.7,
    },
    sessionPerformance: [
      { session: "TOKYO",    winRate: 49.0, pips:  32.1 },
      { session: "LONDON",   winRate: 57.4, pips: 108.5 },
      { session: "NEW_YORK", winRate: 55.8, pips:  74.2 },
    ],
    lossPatterns: [
      { name: "スプレッドスパイク時スリッページ", lossRate: 34, impact: "HIGH"   },
      { name: "逆張りエントリー後の反転",         lossRate: 21, impact: "HIGH"   },
      { name: "低出来高時のチョッピー相場",       lossRate: 12, impact: "MEDIUM" },
    ],
  },
  {
    id: "ea-003",
    name: "TREND FOLLOWER",
    status: "RUNNING",
    strategyType: "DAY_TRADE",
    symbols: ["EURUSD"],
    timeframes: ["H1", "H4"],
    magicNumber: 10003,
    aiRecommendation: {
      recommendation: "RECOMMENDED",
      marketCompatibility: 81,
      reasons: [
        "H4で明確な方向性トレンドを検出",
        "移動平均線のコンフルエンスを確認",
        "リスクリワード比が最適水準",
        "マーケット構造がトレンド継続を支持",
      ],
    },
    performance: {
      totalTrades: 87,
      winRate: 58.9,
      totalPips: 332.1,
      profitFactor: 1.61,
      avgPips: 3.8,
      maxDrawdown: 10.5,
    },
    sessionPerformance: [
      { session: "TOKYO",    winRate: 52.4, pips:  54.8 },
      { session: "LONDON",   winRate: 62.1, pips: 163.7 },
      { session: "NEW_YORK", winRate: 59.3, pips: 113.6 },
    ],
    lossPatterns: [
      { name: "トレンド終焉時のダマシ",   lossRate: 18, impact: "MEDIUM" },
      { name: "ブレイクアウト失敗",       lossRate: 14, impact: "MEDIUM" },
      { name: "週またぎギャップリスク",   lossRate: 8,  impact: "LOW"    },
    ],
  },
  {
    id: "ea-004",
    name: "RANGE EA",
    status: "STOPPED",
    strategyType: "SCALPING",
    symbols: ["GBPUSD"],
    timeframes: ["M15"],
    magicNumber: 10004,
    aiRecommendation: {
      recommendation: "NOT_RECOMMENDED",
      marketCompatibility: 24,
      reasons: [
        "現在トレンド相場 — レンジ戦略は不適合",
        "トレンド環境での勝率が大幅に低下している",
        "現在のボラティリティ局面でドローダウンリスクが高い",
      ],
    },
    performance: {
      totalTrades: 156,
      winRate: 44.1,
      totalPips: -89.3,
      profitFactor: 0.84,
      avgPips: -0.6,
      maxDrawdown: 21.3,
    },
    sessionPerformance: [
      { session: "TOKYO",    winRate: 48.2, pips:  12.4 },
      { session: "LONDON",   winRate: 40.6, pips: -64.8 },
      { session: "NEW_YORK", winRate: 43.7, pips: -36.9 },
    ],
    lossPatterns: [
      { name: "レンジブレイクによる損切り", lossRate: 41, impact: "HIGH"   },
      { name: "トレンド相場へのエントリー", lossRate: 29, impact: "HIGH"   },
      { name: "タイトストップ狩り",         lossRate: 17, impact: "MEDIUM" },
    ],
  },
  {
    id: "ea-005",
    name: "MOMENTUM SWING",
    status: "STOPPED",
    strategyType: "SWING",
    symbols: ["USDJPY"],
    timeframes: ["H4", "D1"],
    magicNumber: 10005,
    aiRecommendation: {
      recommendation: "CAUTION",
      marketCompatibility: 61,
      reasons: [
        "USD/JPYのD1モメンタムが形成中",
        "日銀介入リスクが高まっている",
        "現在のチョッピー相場ではスイング待機が必要",
      ],
    },
    performance: {
      totalTrades: 43,
      winRate: 63.2,
      totalPips: 891.6,
      profitFactor: 2.14,
      avgPips: 20.7,
      maxDrawdown: 12.1,
    },
    sessionPerformance: [
      { session: "TOKYO",    winRate: 67.5, pips: 342.1 },
      { session: "LONDON",   winRate: 58.3, pips: 289.4 },
      { session: "NEW_YORK", winRate: 63.0, pips: 260.1 },
    ],
    lossPatterns: [
      { name: "日銀介入スパイク",         lossRate: 26, impact: "HIGH"   },
      { name: "リスクオフ急反転",         lossRate: 19, impact: "HIGH"   },
      { name: "週末ギャップ",             lossRate: 11, impact: "MEDIUM" },
    ],
  },
];

export const MOCK_AI_SELECTOR_SYMBOL = "EURUSD";
